### ISSUE TITLE
[Bug]: Incorrect version sorting on https://registry.bazel.build/

### ISSUE THREAD

**Issue by derekmauro** [bazelbuild/bazel-central-registry#1370] opened 2024-01-23 20:39 UTC
### What happened?

Attaching a screenshot of https://registry.bazel.build/modules/re2.

Basically the top part of the page shows a copy-paste line with version `2021-09-01`, but the lastest version is `2023-11-01`. In fact the recommended version is yanked.

![bzl_registry](https://github.com/bazelbuild/bazel-central-registry/assets/761129/59172cd5-afee-49a3-aeeb-7d79b04f290f)

### Version

Not relevant, this is a website issue.

**Comment by alexeagle** [comment] 2024-01-23 20:47
Yeah this module doesn't use semver syntax, i think this is another follow-up to https://github.com/bazel-contrib/bcr-ui/pull/56 likely caused by https://github.com/bazel-contrib/bcr-ui/pull/55.

Maybe only this one module is affected?

**Comment by Wyverald** [comment] 2024-01-23 20:55
Dupe of https://github.com/bazel-contrib/bcr-ui/issues/54

**Closed by Wyverald** 2024-01-23 20:55 UTC
Labels: bug
