### ISSUE TITLE
`./tools/add_module.py` depends on `yaml` but this is not documented

### ISSUE THREAD

**Issue by shs96c** [bazelbuild/bazel-central-registry#54] opened 2022-01-07 11:38 UTC
Not only does `add_module.py` depend on `colorama` (#46) but it also has an undeclared dependency on `yaml`.

If we really believe that `bzlmod` is sufficient for developers, this should be handled by a `MODULE.bazel` file that uses `rules_python` to import the required third party deps, and then a simple `bazel run //tools:add_module` should be enough to bootstrap a new dependency. But configuring everything in the `WORKSPACE.bazel` file would be fine too :)

**Comment by Wyverald** [comment] 2022-01-07 15:14
Marking as dupe of #46.

**Closed by Wyverald** 2022-01-07 15:14 UTC
