### ISSUE TITLE
wanted: com_google_protobuf

### ISSUE THREAD

**Issue by alexeagle** [bazelbuild/bazel-central-registry#320] opened 2022-12-12 15:31 UTC
### Module location

https://github.com/protocolbuffers/protobuf

### Any other context to provide?

@yannic says this is the next step to unblocking rules_proto usage in bzlmod.

### Fund our work

- [ ] Sponsor our community's open source work by donating a [feature bounty](https://opencollective.com/bazel-rules-authors-sig/projects/bazel-central-registry)

**Comment by comius** [comment] 2022-12-12 15:32
Actually I'm working on this. What's missing is rules_kotlin.

**Comment by meteorcloudy** [comment] 2022-12-12 16:02
@comius Do we also have someone from the protobuf team looking into supporting Bzlmod?

**Comment by meteorcloudy** [comment] 2022-12-13 09:21
> rules_jvm_external.4.5

It looks like you are using an old version of Bazel, can you try again with the [latest 6.0 rc](https://releases.bazel.build/6.0.0/rc4/index.html)? If it still doesn't work, please try to file an issue to https://github.com/bazelbuild/rules_jvm_external and provide a reproducible case.

**Comment by meteorcloudy** [comment] 2022-12-14 09:50
> 4.5 seems to be the version available on: [Bazel Central Register](https://registry.bazel.build/modules/rules_jvm_external) and on [Github](https://github.com/bazelbuild/rules_jvm_external/releases), isn't it ?

Yes, that's the latest rules_jvm_external version. You'll also need to the latest bazel version ;)

With Bzlmod, we have stricter repository name validation, probably some repo name needs to be fixed in rules_kotlin.

**Comment by meteorcloudy** [comment] 2022-12-14 09:51
But can you remove the rules_kotlin dependencies in WORKSPACE.bzlmod, I don't see why fixing protobuf needs rules_kotlin to work.

**Comment by meteorcloudy** [comment] 2022-12-14 10:37
I see, then this probably has to wait for https://github.com/bazelbuild/rules_kotlin/pull/878

**Comment by comius** [comment] 2022-12-20 13:38
I added more info on what needs to happen on rules_kotlin in https://github.com/bazelbuild/rules_kotlin/issues/660

> Do we also have someone from the protobuf team looking into supporting Bzlmod?

Not anybody in particular, but I've heard they are interested.

**Comment by meteorcloudy** [comment] 2023-05-16 17:14
Looks like the protobuf team currently doesn't have bandwidth for https://github.com/protocolbuffers/protobuf/issues/12184

**Comment by Clement-Jean** [comment] 2023-05-23 02:13
Turns out rules_python and rules_jvm_external are not compatible yet. Protobuf relies on rules_python@0.14.0 which is broken in the registry and rules_jvm_external@5.2 gives the kotlin error shown in the previous comment.

However, I have temporarily added them into the WORKSPACE.bzlmod. It seems that it is working, how could I test this further?

**Comment by malt3** [comment] 2023-08-31 07:18
Relevant upstream issue: https://github.com/protocolbuffers/protobuf/issues/13618

It looks like things are beginning to move! Thank you to everyone involved ❤️

**Comment by chrislovecnm** [comment] 2023-11-05 16:58
Anyone have a status?

**Comment by bgdnvk** [comment] 2023-12-06 12:11
bump
ive been running into issues with gazelle here by using bazel module

**Comment by Wyverald** [comment] 2024-07-23 23:12
`protobuf` is now maintained by the protobuf team from Google.

**Closed by Wyverald** 2024-07-23 23:12 UTC
Labels: bounty-1000USD, module wanted
